// @copyright Trollwerks Inc.

import CoreLocation
@testable import MTP

// generated by https://github.com/seanhenry/SwiftMockGeneratorForXcode
// swiftlint:disable all

final class LocationServiceSpy: LocationService {
    var invokedHereGetter = false
    var invokedHereGetterCount = 0
    var stubbedHere: CLLocationCoordinate2D!
    var here: CLLocationCoordinate2D? {
        invokedHereGetter = true
        invokedHereGetterCount += 1
        return stubbedHere
    }
    var invokedInsideGetter = false
    var invokedInsideGetterCount = 0
    var stubbedInside: Location!
    var inside: Location? {
        invokedInsideGetter = true
        invokedInsideGetterCount += 1
        return stubbedInside
    }
    var invokedDistancesGetter = false
    var invokedDistancesGetterCount = 0
    var stubbedDistances: Distances!
    var distances: Distances {
        invokedDistancesGetter = true
        invokedDistancesGetterCount += 1
        return stubbedDistances
    }
    var invokedMappablesGetter = false
    var invokedMappablesGetterCount = 0
    var stubbedMappables: Set<MapInfo>! = []
    var mappables: Set<MapInfo> {
        invokedMappablesGetter = true
        invokedMappablesGetterCount += 1
        return stubbedMappables
    }
    var invokedAppGetter = false
    var invokedAppGetterCount = 0
    var stubbedApp: ApplicationService!
    var app: ApplicationService {
        invokedAppGetter = true
        invokedAppGetterCount += 1
        return stubbedApp
    }
    var invokedDataGetter = false
    var invokedDataGetterCount = 0
    var stubbedData: DataService!
    var data: DataService {
        invokedDataGetter = true
        invokedDataGetterCount += 1
        return stubbedData
    }
    var invokedLocGetter = false
    var invokedLocGetterCount = 0
    var stubbedLoc: LocationService!
    var loc: LocationService {
        invokedLocGetter = true
        invokedLocGetterCount += 1
        return stubbedLoc
    }
    var invokedLogGetter = false
    var invokedLogGetterCount = 0
    var stubbedLog: LoggingService!
    var log: LoggingService {
        invokedLogGetter = true
        invokedLogGetterCount += 1
        return stubbedLog
    }
    var invokedMtpGetter = false
    var invokedMtpGetterCount = 0
    var stubbedMtp: MTPNetworkService!
    var mtp: MTPNetworkService {
        invokedMtpGetter = true
        invokedMtpGetterCount += 1
        return stubbedMtp
    }
    var invokedNoteGetter = false
    var invokedNoteGetterCount = 0
    var stubbedNote: NotificationService!
    var note: NotificationService {
        invokedNoteGetter = true
        invokedNoteGetterCount += 1
        return stubbedNote
    }
    var invokedReveal = false
    var invokedRevealCount = 0
    var invokedRevealParameters: (place: MapInfo?, callout: Bool)?
    var invokedRevealParametersList = [(place: MapInfo?, callout: Bool)]()
    func reveal(place: MapInfo?, callout: Bool) {
        invokedReveal = true
        invokedRevealCount += 1
        invokedRevealParameters = (place, callout)
        invokedRevealParametersList.append((place, callout))
    }
    var invokedUpdate = false
    var invokedUpdateCount = 0
    var invokedUpdateParameters: (place: MapInfo, Void)?
    var invokedUpdateParametersList = [(place: MapInfo, Void)]()
    func update(place: MapInfo) {
        invokedUpdate = true
        invokedUpdateCount += 1
        invokedUpdateParameters = (place, ())
        invokedUpdateParametersList.append((place, ()))
    }
    var invokedNearest = false
    var invokedNearestCount = 0
    var invokedNearestParameters: (list: Checklist, id: Int, coordinate: CLLocationCoordinate2D)?
    var invokedNearestParametersList = [(list: Checklist, id: Int, coordinate: CLLocationCoordinate2D)]()
    var stubbedNearestResult: MapInfo!
    func nearest(list: Checklist,
    id: Int,
    to coordinate: CLLocationCoordinate2D) -> MapInfo? {
        invokedNearest = true
        invokedNearestCount += 1
        invokedNearestParameters = (list, id, coordinate)
        invokedNearestParametersList.append((list, id, coordinate))
        return stubbedNearestResult
    }
    var invokedMappablesList = false
    var invokedMappablesListCount = 0
    var invokedMappablesListParameters: (list: Checklist, Void)?
    var invokedMappablesListParametersList = [(list: Checklist, Void)]()
    var stubbedMappablesListResult: Set<MapInfo>! = []
    func mappables(list: Checklist) -> Set<MapInfo> {
        invokedMappablesList = true
        invokedMappablesListCount += 1
        invokedMappablesListParameters = (list, ())
        invokedMappablesListParametersList.append((list, ()))
        return stubbedMappablesListResult
    }
    var invokedInsert = false
    var invokedInsertCount = 0
    var invokedInsertParameters: (tracker: Any, Void)?
    var invokedInsertParametersList = [(tracker: Any, Void)]()
    func insert<T>(tracker: T) where T: LocationTracker, T: Hashable {
        invokedInsert = true
        invokedInsertCount += 1
        invokedInsertParameters = (tracker, ())
        invokedInsertParametersList.append((tracker, ()))
    }
    var invokedRemove = false
    var invokedRemoveCount = 0
    var invokedRemoveParameters: (tracker: Any, Void)?
    var invokedRemoveParametersList = [(tracker: Any, Void)]()
    func remove<T>(tracker: T) where T: LocationTracker, T: Hashable {
        invokedRemove = true
        invokedRemoveCount += 1
        invokedRemoveParameters = (tracker, ())
        invokedRemoveParametersList.append((tracker, ()))
    }
    var invokedRequest = false
    var invokedRequestCount = 0
    var invokedRequestParameters: (permission: LocationPermission, Void)?
    var invokedRequestParametersList = [(permission: LocationPermission, Void)]()
    func request(permission: LocationPermission) {
        invokedRequest = true
        invokedRequestCount += 1
        invokedRequestParameters = (permission, ())
        invokedRequestParametersList.append((permission, ()))
    }
    var invokedStart = false
    var invokedStartCount = 0
    var invokedStartParameters: (permission: LocationPermission, Void)?
    var invokedStartParametersList = [(permission: LocationPermission, Void)]()
    func start(permission: LocationPermission) {
        invokedStart = true
        invokedStartCount += 1
        invokedStartParameters = (permission, ())
        invokedStartParametersList.append((permission, ()))
    }
    var invokedInject = false
    var invokedInjectCount = 0
    var invokedInjectParameters: (handler: LocationHandler, Void)?
    var invokedInjectParametersList = [(handler: LocationHandler, Void)]()
    func inject(handler: LocationHandler) {
        invokedInject = true
        invokedInjectCount += 1
        invokedInjectParameters = (handler, ())
        invokedInjectParametersList.append((handler, ()))
    }
}
