// @copyright Trollwerks Inc.

@testable import MTP

// generated by https://github.com/seanhenry/SwiftMockGeneratorForXcode
// swiftlint:disable all

final class MTPNetworkServiceSpy: MTPNetworkService {
    var invokedCheck = false
    var invokedCheckCount = 0
    var invokedCheckParameters: (list: Checklist, id: Int, visited: Bool, then: MTPResult<Bool>)?
    var invokedCheckParametersList = [(list: Checklist, id: Int, visited: Bool, then: MTPResult<Bool>)]()
    func check(list: Checklist,
    id: Int,
    visited: Bool,
    then: @escaping MTPResult<Bool>) {
        invokedCheck = true
        invokedCheckCount += 1
        invokedCheckParameters = (list, id, visited, then)
        invokedCheckParametersList.append((list, id, visited, then))
    }
    var invokedLoadPhotosLocation = false
    var invokedLoadPhotosLocationCount = 0
    var invokedLoadPhotosLocationParameters: (id: Int, reload: Bool, then: MTPResult<PhotosInfoJSON>)?
    var invokedLoadPhotosLocationParametersList = [(id: Int, reload: Bool, then: MTPResult<PhotosInfoJSON>)]()
    func loadPhotos(location id: Int,
    reload: Bool,
    then: @escaping MTPResult<PhotosInfoJSON>) {
        invokedLoadPhotosLocation = true
        invokedLoadPhotosLocationCount += 1
        invokedLoadPhotosLocationParameters = (id, reload, then)
        invokedLoadPhotosLocationParametersList.append((id, reload, then))
    }
    var invokedLoadPhotosPage = false
    var invokedLoadPhotosPageCount = 0
    var invokedLoadPhotosPageParameters: (page: Int, reload: Bool, then: MTPResult<PhotosPageInfoJSON>)?
    var invokedLoadPhotosPageParametersList = [(page: Int, reload: Bool, then: MTPResult<PhotosPageInfoJSON>)]()
    func loadPhotos(page: Int,
    reload: Bool,
    then: @escaping MTPResult<PhotosPageInfoJSON>) {
        invokedLoadPhotosPage = true
        invokedLoadPhotosPageCount += 1
        invokedLoadPhotosPageParameters = (page, reload, then)
        invokedLoadPhotosPageParametersList.append((page, reload, then))
    }
    var invokedLoadPhotosProfile = false
    var invokedLoadPhotosProfileCount = 0
    var invokedLoadPhotosProfileParameters: (id: Int, page: Int, reload: Bool, then: MTPResult<PhotosPageInfoJSON>)?
    var invokedLoadPhotosProfileParametersList = [(id: Int, page: Int, reload: Bool, then: MTPResult<PhotosPageInfoJSON>)]()
    func loadPhotos(profile id: Int,
    page: Int,
    reload: Bool,
    then: @escaping MTPResult<PhotosPageInfoJSON>) {
        invokedLoadPhotosProfile = true
        invokedLoadPhotosProfileCount += 1
        invokedLoadPhotosProfileParameters = (id, page, reload, then)
        invokedLoadPhotosProfileParametersList.append((id, page, reload, then))
    }
    var invokedLoadPostsLocation = false
    var invokedLoadPostsLocationCount = 0
    var invokedLoadPostsLocationParameters: (id: Int, then: MTPResult<PostsJSON>)?
    var invokedLoadPostsLocationParametersList = [(id: Int, then: MTPResult<PostsJSON>)]()
    func loadPosts(location id: Int,
    then: @escaping MTPResult<PostsJSON>) {
        invokedLoadPostsLocation = true
        invokedLoadPostsLocationCount += 1
        invokedLoadPostsLocationParameters = (id, then)
        invokedLoadPostsLocationParametersList.append((id, then))
    }
    var invokedLoadPostsUser = false
    var invokedLoadPostsUserCount = 0
    var invokedLoadPostsUserParameters: (id: Int, then: MTPResult<PostsJSON>)?
    var invokedLoadPostsUserParametersList = [(id: Int, then: MTPResult<PostsJSON>)]()
    func loadPosts(user id: Int,
    then: @escaping MTPResult<PostsJSON>) {
        invokedLoadPostsUser = true
        invokedLoadPostsUserCount += 1
        invokedLoadPostsUserParameters = (id, then)
        invokedLoadPostsUserParametersList.append((id, then))
    }
    var invokedLoadRankings = false
    var invokedLoadRankingsCount = 0
    var invokedLoadRankingsParameters: (query: RankingsQuery, then: MTPResult<RankingsPageInfoJSON>)?
    var invokedLoadRankingsParametersList = [(query: RankingsQuery, then: MTPResult<RankingsPageInfoJSON>)]()
    func loadRankings(query: RankingsQuery,
    then: @escaping MTPResult<RankingsPageInfoJSON>) {
        invokedLoadRankings = true
        invokedLoadRankingsCount += 1
        invokedLoadRankingsParameters = (query, then)
        invokedLoadRankingsParametersList.append((query, then))
    }
    var invokedLoadScorecard = false
    var invokedLoadScorecardCount = 0
    var invokedLoadScorecardParameters: (list: Checklist, id: Int, then: MTPResult<ScorecardJSON>)?
    var invokedLoadScorecardParametersList = [(list: Checklist, id: Int, then: MTPResult<ScorecardJSON>)]()
    func loadScorecard(list: Checklist,
    user id: Int,
    then: @escaping MTPResult<ScorecardJSON>) {
        invokedLoadScorecard = true
        invokedLoadScorecardCount += 1
        invokedLoadScorecardParameters = (list, id, then)
        invokedLoadScorecardParametersList.append((list, id, then))
    }
    var invokedLoadUser = false
    var invokedLoadUserCount = 0
    var invokedLoadUserParameters: (id: Int, then: MTPResult<UserJSON>)?
    var invokedLoadUserParametersList = [(id: Int, then: MTPResult<UserJSON>)]()
    func loadUser(id: Int,
    then: @escaping MTPResult<UserJSON>) {
        invokedLoadUser = true
        invokedLoadUserCount += 1
        invokedLoadUserParameters = (id, then)
        invokedLoadUserParametersList.append((id, then))
    }
    var invokedSearch = false
    var invokedSearchCount = 0
    var invokedSearchParameters: (query: String, then: MTPResult<SearchResultJSON>)?
    var invokedSearchParametersList = [(query: String, then: MTPResult<SearchResultJSON>)]()
    func search(query: String,
    then: @escaping MTPResult<SearchResultJSON>) {
        invokedSearch = true
        invokedSearchCount += 1
        invokedSearchParameters = (query, then)
        invokedSearchParametersList.append((query, then))
    }
    var invokedUpload = false
    var invokedUploadCount = 0
    var invokedUploadParameters: (photo: Data, caption: String?, id: Int?, then: MTPResult<PhotoReply>)?
    var invokedUploadParametersList = [(photo: Data, caption: String?, id: Int?, then: MTPResult<PhotoReply>)]()
    func upload(photo: Data,
    caption: String?,
    location id: Int?,
    then: @escaping MTPResult<PhotoReply>) {
        invokedUpload = true
        invokedUploadCount += 1
        invokedUploadParameters = (photo, caption, id, then)
        invokedUploadParametersList.append((photo, caption, id, then))
    }
    var invokedPostPublish = false
    var invokedPostPublishCount = 0
    var invokedPostPublishParameters: (payload: PostPayload, then: MTPResult<PostReply>)?
    var invokedPostPublishParametersList = [(payload: PostPayload, then: MTPResult<PostReply>)]()
    func postPublish(payload: PostPayload,
    then: @escaping MTPResult<PostReply>) {
        invokedPostPublish = true
        invokedPostPublishCount += 1
        invokedPostPublishParameters = (payload, then)
        invokedPostPublishParametersList.append((payload, then))
    }
    var invokedUserDeleteAccount = false
    var invokedUserDeleteAccountCount = 0
    var invokedUserDeleteAccountParameters: (then: MTPResult<String>, Void)?
    var invokedUserDeleteAccountParametersList = [(then: MTPResult<String>, Void)]()
    func userDeleteAccount(then: @escaping MTPResult<String>) {
        invokedUserDeleteAccount = true
        invokedUserDeleteAccountCount += 1
        invokedUserDeleteAccountParameters = (then, ())
        invokedUserDeleteAccountParametersList.append((then, ()))
    }
    var invokedUserForgotPassword = false
    var invokedUserForgotPasswordCount = 0
    var invokedUserForgotPasswordParameters: (email: String, then: MTPResult<String>)?
    var invokedUserForgotPasswordParametersList = [(email: String, then: MTPResult<String>)]()
    func userForgotPassword(email: String,
    then: @escaping MTPResult<String>) {
        invokedUserForgotPassword = true
        invokedUserForgotPasswordCount += 1
        invokedUserForgotPasswordParameters = (email, then)
        invokedUserForgotPasswordParametersList.append((email, then))
    }
    var invokedUserLogin = false
    var invokedUserLoginCount = 0
    var invokedUserLoginParameters: (email: String, password: String, then: MTPResult<UserJSON>)?
    var invokedUserLoginParametersList = [(email: String, password: String, then: MTPResult<UserJSON>)]()
    func userLogin(email: String,
    password: String,
    then: @escaping MTPResult<UserJSON>) {
        invokedUserLogin = true
        invokedUserLoginCount += 1
        invokedUserLoginParameters = (email, password, then)
        invokedUserLoginParametersList.append((email, password, then))
    }
    var invokedUserRegister = false
    var invokedUserRegisterCount = 0
    var invokedUserRegisterParameters: (payload: RegistrationPayload, then: MTPResult<UserJSON>)?
    var invokedUserRegisterParametersList = [(payload: RegistrationPayload, then: MTPResult<UserJSON>)]()
    func userRegister(payload: RegistrationPayload,
    then: @escaping MTPResult<UserJSON>) {
        invokedUserRegister = true
        invokedUserRegisterCount += 1
        invokedUserRegisterParameters = (payload, then)
        invokedUserRegisterParametersList.append((payload, then))
    }
    var invokedUserUpdate = false
    var invokedUserUpdateCount = 0
    var invokedUserUpdateParameters: (payload: UserUpdatePayload, then: MTPResult<UserJSON>)?
    var invokedUserUpdateParametersList = [(payload: UserUpdatePayload, then: MTPResult<UserJSON>)]()
    func userUpdate(payload: UserUpdatePayload,
    then: @escaping MTPResult<UserJSON>) {
        invokedUserUpdate = true
        invokedUserUpdateCount += 1
        invokedUserUpdateParameters = (payload, then)
        invokedUserUpdateParametersList.append((payload, then))
    }
    var invokedRefreshEverything = false
    var invokedRefreshEverythingCount = 0
    func refreshEverything() {
        invokedRefreshEverything = true
        invokedRefreshEverythingCount += 1
    }
    var invokedRefreshRankings = false
    var invokedRefreshRankingsCount = 0
    func refreshRankings() {
        invokedRefreshRankings = true
        invokedRefreshRankingsCount += 1
    }
}
