// @copyright Trollwerks Inc.

@testable import MTP

// generated by https://github.com/seanhenry/SwiftMockGeneratorForXcode
// swiftlint:disable all

final class NotificationServiceSpy: NotificationService {
    var invokedAuthorizeNotifications = false
    var invokedAuthorizeNotificationsCount = 0
    var stubbedAuthorizeNotificationsThenResult: (Bool, Void)?
    func authorizeNotifications(then: @escaping (Bool) -> Void) {
        invokedAuthorizeNotifications = true
        invokedAuthorizeNotificationsCount += 1
        if let result = stubbedAuthorizeNotificationsThenResult {
            then(result.0)
        }
    }
    var invokedAsk = false
    var invokedAskCount = 0
    var invokedAskParameters: (question: String, Void)?
    var invokedAskParametersList = [(question: String, Void)]()
    var stubbedAskThenResult: (Bool, Void)?
    func ask(question: String,
    then: @escaping (Bool) -> Void) {
        invokedAsk = true
        invokedAskCount += 1
        invokedAskParameters = (question, ())
        invokedAskParametersList.append((question, ()))
        if let result = stubbedAskThenResult {
            then(result.0)
        }
    }
    var invokedCheckTriggered = false
    var invokedCheckTriggeredCount = 0
    func checkTriggered() {
        invokedCheckTriggered = true
        invokedCheckTriggeredCount += 1
    }
    var invokedNotify = false
    var invokedNotifyCount = 0
    var invokedNotifyParameters: (item: Checklist.Item, triggered: Date)?
    var invokedNotifyParametersList = [(item: Checklist.Item, triggered: Date)]()
    func notify(item: Checklist.Item,
    triggered: Date) {
        invokedNotify = true
        invokedNotifyCount += 1
        invokedNotifyParameters = (item, triggered)
        invokedNotifyParametersList.append((item, triggered))
    }
    var invokedNotifyList = false
    var invokedNotifyListCount = 0
    var invokedNotifyListParameters: (list: Checklist, info: PlaceInfo, triggered: Date)?
    var invokedNotifyListParametersList = [(list: Checklist, info: PlaceInfo, triggered: Date)]()
    func notify(list: Checklist,
    info: PlaceInfo,
    triggered: Date) {
        invokedNotifyList = true
        invokedNotifyListCount += 1
        invokedNotifyListParameters = (list, info, triggered)
        invokedNotifyListParametersList.append((list, info, triggered))
    }
    var invokedCongratulate = false
    var invokedCongratulateCount = 0
    var invokedCongratulateParameters: (item: Checklist.Item, Void)?
    var invokedCongratulateParametersList = [(item: Checklist.Item, Void)]()
    func congratulate(item: Checklist.Item) {
        invokedCongratulate = true
        invokedCongratulateCount += 1
        invokedCongratulateParameters = (item, ())
        invokedCongratulateParametersList.append((item, ()))
    }
    var invokedInfoBackground = false
    var invokedInfoBackgroundCount = 0
    var invokedInfoBackgroundParameters: (title: String?, body: String?)?
    var invokedInfoBackgroundParametersList = [(title: String?, body: String?)]()
    func infoBackground(title: String?,
    body: String?) {
        invokedInfoBackground = true
        invokedInfoBackgroundCount += 1
        invokedInfoBackgroundParameters = (title, body)
        invokedInfoBackgroundParametersList.append((title, body))
    }
    var invokedVisitBackground = false
    var invokedVisitBackgroundCount = 0
    var invokedVisitBackgroundParameters: (title: String, body: String, info: Info)?
    var invokedVisitBackgroundParametersList = [(title: String, body: String, info: Info)]()
    func visitBackground(title: String,
    body: String,
    info: Info) {
        invokedVisitBackground = true
        invokedVisitBackgroundCount += 1
        invokedVisitBackgroundParameters = (title, body, info)
        invokedVisitBackgroundParametersList.append((title, body, info))
    }
    var invokedBackground = false
    var invokedBackgroundCount = 0
    var shouldInvokeBackgroundThen = false
    func background(then: @escaping () -> Void) {
        invokedBackground = true
        invokedBackgroundCount += 1
        if shouldInvokeBackgroundThen {
            then()
        }
    }
    var invokedPost = false
    var invokedPostCount = 0
    var invokedPostParameters: (title: String, subtitle: String, body: String, category: String, info: Info)?
    var invokedPostParametersList = [(title: String, subtitle: String, body: String, category: String, info: Info)]()
    func post(title: String,
    subtitle: String,
    body: String,
    category: String,
    info: Info) {
        invokedPost = true
        invokedPostCount += 1
        invokedPostParameters = (title, subtitle, body, category, info)
        invokedPostParametersList.append((title, subtitle, body, category, info))
    }
    var invokedModalError = false
    var invokedModalErrorCount = 0
    var invokedModalErrorParameters: (error: String, Void)?
    var invokedModalErrorParametersList = [(error: String, Void)]()
    func modal(error: String) {
        invokedModalError = true
        invokedModalErrorCount += 1
        invokedModalErrorParameters = (error, ())
        invokedModalErrorParametersList.append((error, ()))
    }
    var invokedModalInfo = false
    var invokedModalInfoCount = 0
    var invokedModalInfoParameters: (info: String, Void)?
    var invokedModalInfoParametersList = [(info: String, Void)]()
    func modal(info: String) {
        invokedModalInfo = true
        invokedModalInfoCount += 1
        invokedModalInfoParameters = (info, ())
        invokedModalInfoParametersList.append((info, ()))
    }
    var invokedModalSuccess = false
    var invokedModalSuccessCount = 0
    var invokedModalSuccessParameters: (success: String, Void)?
    var invokedModalSuccessParametersList = [(success: String, Void)]()
    func modal(success: String) {
        invokedModalSuccess = true
        invokedModalSuccessCount += 1
        invokedModalSuccessParameters = (success, ())
        invokedModalSuccessParametersList.append((success, ()))
    }
    var invokedDismissModal = false
    var invokedDismissModalCount = 0
    func dismissModal() {
        invokedDismissModal = true
        invokedDismissModalCount += 1
    }
    var invokedMessage = false
    var invokedMessageCount = 0
    var invokedMessageParameters: (error: String, Void)?
    var invokedMessageParametersList = [(error: String, Void)]()
    func message(error: String) {
        invokedMessage = true
        invokedMessageCount += 1
        invokedMessageParameters = (error, ())
        invokedMessageParametersList.append((error, ()))
    }
    var invokedUnimplemented = false
    var invokedUnimplementedCount = 0
    func unimplemented() {
        invokedUnimplemented = true
        invokedUnimplementedCount += 1
    }
}
