module: MTP
module_version: 1.0

author: Alex Curylo
author_url: http://everywhs.com
github_url: https://github.com/alexcurylo/mtp
github_file_prefix: https://github.com/alexcurylo/mtp/tree/master

theme: fullwidth
clean: true

readme: README.md
copyright: '© 2018-present [Trollwerks Inc.](http://trollwerks.com/) under [MIT license](https://github.com/alexcurylo/mtp/blob/master/LICENSE.md).'

skip_undocumented: false
hide_documentation_coverage: false
min_acl: private

swift_version: 4.2
sdk: iphonesimulator
xcodebuild_arguments:
  - -workspace
  - MTP.xcworkspace
  - -scheme
  - MTP

output: docs/
