source 'https://rubygems.org'

gem 'cocoapods'
gem 'cocoapods-acknowledgements'
gem 'cocoapods-check'
gem 'danger'
gem 'danger-slather'
gem 'danger-swiftlint'
gem 'danger-xcode_summary'
gem 'danger-xcov'
gem 'fastlane'
gem 'jazzy'
gem 'slather'
gem 'xcpretty'
gem 'xcpretty-json-formatter'
gem 'xcpretty-travis-formatter'
