// @copyright Trollwerks Inc.

@testable import MTP

// generated by https://github.com/seanhenry/SwiftMockGeneratorForXcode
// swiftlint:disable all

final class SpyApplicationService: ApplicationService {
    var invokedLaunch = false
    var invokedLaunchCount = 0
    var invokedLaunchParameters: (url: URL, Void)?
    var invokedLaunchParametersList = [(url: URL, Void)]()
    func launch(url: URL) {
        invokedLaunch = true
        invokedLaunchCount += 1
        invokedLaunchParameters = (url, ())
        invokedLaunchParametersList.append((url, ()))
    }
}
