// @copyright Trollwerks Inc.

@testable import MTP

// generated by https://github.com/seanhenry/SwiftMockGeneratorForXcode
// swiftlint:disable all

final class SpyApplicationService: ApplicationService {
    var invokedLaunch = false
    var invokedLaunchCount = 0
    var invokedLaunchParameters: (url: URL, Void)?
    var invokedLaunchParametersList = [(url: URL, Void)]()
    func launch(url: URL) {
        invokedLaunch = true
        invokedLaunchCount += 1
        invokedLaunchParameters = (url, ())
        invokedLaunchParametersList.append((url, ()))
    }
    var invokedRouteToPlaceAnnotation = false
    var invokedRouteToPlaceAnnotationCount = 0
    var invokedRouteToPlaceAnnotationParameters: (annotation: PlaceAnnotation, Void)?
    var invokedRouteToPlaceAnnotationParametersList = [(annotation: PlaceAnnotation, Void)]()
    func route(to annotation: PlaceAnnotation) {
        invokedRouteToPlaceAnnotation = true
        invokedRouteToPlaceAnnotationCount += 1
        invokedRouteToPlaceAnnotationParameters = (annotation, ())
        invokedRouteToPlaceAnnotationParametersList.append((annotation, ()))
    }
    var invokedRouteToUser = false
    var invokedRouteToUserCount = 0
    var invokedRouteToUserParameters: (user: User?, Void)?
    var invokedRouteToUserParametersList = [(user: User?, Void)]()
    func route(to user: User?) {
        invokedRouteToUser = true
        invokedRouteToUserCount += 1
        invokedRouteToUserParameters = (user, ())
        invokedRouteToUserParametersList.append((user, ()))
    }
    var invokedEndEditing = false
    var invokedEndEditingCount = 0
    func endEditing() {
        invokedEndEditing = true
        invokedEndEditingCount += 1
    }
}
