// @copyright Trollwerks Inc.

@testable import MTP

// generated by https://github.com/seanhenry/SwiftMockGeneratorForXcode
// swiftlint:disable all

final class ApplicationServiceSpy: ApplicationService {
    var invokedLaunch = false
    var invokedLaunchCount = 0
    var invokedLaunchParameters: (url: URL, Void)?
    var invokedLaunchParametersList = [(url: URL, Void)]()
    func launch(url: URL) {
        invokedLaunch = true
        invokedLaunchCount += 1
        invokedLaunchParameters = (url, ())
        invokedLaunchParametersList.append((url, ()))
    }
    var invokedRouteReveal = false
    var invokedRouteRevealCount = 0
    var invokedRouteRevealParameters: (mappable: Mappable, Void)?
    var invokedRouteRevealParametersList = [(mappable: Mappable, Void)]()
    func route(reveal mappable: Mappable) {
        invokedRouteReveal = true
        invokedRouteRevealCount += 1
        invokedRouteRevealParameters = (mappable, ())
        invokedRouteRevealParametersList.append((mappable, ()))
    }
    var invokedRouteShow = false
    var invokedRouteShowCount = 0
    var invokedRouteShowParameters: (mappable: Mappable, Void)?
    var invokedRouteShowParametersList = [(mappable: Mappable, Void)]()
    func route(show mappable: Mappable) {
        invokedRouteShow = true
        invokedRouteShowCount += 1
        invokedRouteShowParameters = (mappable, ())
        invokedRouteShowParametersList.append((mappable, ()))
    }
    var invokedRouteTo = false
    var invokedRouteToCount = 0
    var invokedRouteToParameters: (route: Route, Void)?
    var invokedRouteToParametersList = [(route: Route, Void)]()
    func route(to route: Route) {
        invokedRouteTo = true
        invokedRouteToCount += 1
        invokedRouteToParameters = (route, ())
        invokedRouteToParametersList.append((route, ()))
    }
    var invokedEndEditing = false
    var invokedEndEditingCount = 0
    func endEditing() {
        invokedEndEditing = true
        invokedEndEditingCount += 1
    }
    var invokedDismissPresentations = false
    var invokedDismissPresentationsCount = 0
    func dismissPresentations() {
        invokedDismissPresentations = true
        invokedDismissPresentationsCount += 1
    }
}
