// @copyright Trollwerks Inc.

import CoreLocation
@testable import MTP

// generated by https://github.com/seanhenry/SwiftMockGeneratorForXcode
// swiftlint:disable all

final class LocationsVCSpy: LocationsVC {
    var invokedViewDidLoad = false
    var invokedViewDidLoadCount = 0
    override func viewDidLoad() {
        invokedViewDidLoad = true
        invokedViewDidLoadCount += 1
    }
    var invokedViewWillAppear = false
    var invokedViewWillAppearCount = 0
    var invokedViewWillAppearParameters: (animated: Bool, Void)?
    var invokedViewWillAppearParametersList = [(animated: Bool, Void)]()
    override func viewWillAppear(_ animated: Bool) {
        invokedViewWillAppear = true
        invokedViewWillAppearCount += 1
        invokedViewWillAppearParameters = (animated, ())
        invokedViewWillAppearParametersList.append((animated, ()))
    }
    var invokedViewDidAppear = false
    var invokedViewDidAppearCount = 0
    var invokedViewDidAppearParameters: (animated: Bool, Void)?
    var invokedViewDidAppearParametersList = [(animated: Bool, Void)]()
    override func viewDidAppear(_ animated: Bool) {
        invokedViewDidAppear = true
        invokedViewDidAppearCount += 1
        invokedViewDidAppearParameters = (animated, ())
        invokedViewDidAppearParametersList.append((animated, ()))
    }
    var invokedPrepare = false
    var invokedPrepareCount = 0
    var invokedPrepareParameters: (segue: UIStoryboardSegue, sender: Any?)?
    var invokedPrepareParametersList = [(segue: UIStoryboardSegue, sender: Any?)]()
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        invokedPrepare = true
        invokedPrepareCount += 1
        invokedPrepareParameters = (segue, sender)
        invokedPrepareParametersList.append((segue, sender))
    }
    var invokedUpdateFilter = false
    var invokedUpdateFilterCount = 0
    override func updateFilter() {
        invokedUpdateFilter = true
        invokedUpdateFilterCount += 1
    }
    var invokedReveal = false
    var invokedRevealCount = 0
    var invokedRevealParameters: (user: User?, Void)?
    var invokedRevealParametersList = [(user: User?, Void)]()
    override func reveal(user: User?) {
        invokedReveal = true
        invokedRevealCount += 1
        invokedRevealParameters = (user, ())
        invokedRevealParametersList.append((user, ()))
    }
}
