// @copyright Trollwerks Inc.

@testable import MTP

// generated by https://github.com/seanhenry/SwiftMockGeneratorForXcode
// swiftlint:disable all

final class ReportingServiceSpy: ReportingService {
    var invokedReport = false
    var invokedReportCount = 0
    var invokedReportParameters: (event: AnalyticsEvent, Void)?
    var invokedReportParametersList = [(event: AnalyticsEvent, Void)]()
    func report(event: AnalyticsEvent) {
        invokedReport = true
        invokedReportCount += 1
        invokedReportParameters = (event, ())
        invokedReportParametersList.append((event, ()))
    }
    var invokedSet = false
    var invokedSetCount = 0
    var invokedSetParameters: (userId: String, Void)?
    var invokedSetParametersList = [(userId: String, Void)]()
    func set(userId: String) {
        invokedSet = true
        invokedSetCount += 1
        invokedSetParameters = (userId, ())
        invokedSetParametersList.append((userId, ()))
    }
}
