// @copyright Trollwerks Inc.

@testable import MTP

// generated by https://github.com/seanhenry/SwiftMockGeneratorForXcode
// swiftlint:disable all

final class StyleServiceSpy: StyleService {
    var invokedStylerGetter = false
    var invokedStylerGetterCount = 0
    var stubbedStyler: Styler.Type!
    var styler: Styler.Type {
        invokedStylerGetter = true
        invokedStylerGetterCount += 1
        return stubbedStyler
    }
}
