# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
# required
  "iPhone 8 Plus", # 5.5" phone
  "iPhone Xs Max", # 6.5" phone
  # "iPhone XS Max", # 6.5" phone # if Xs Max fails
  "iPad Pro (12.9-inch) (2nd generation)",
  # https://github.com/fastlane/frameit-frames/pull/8
  "iPad Pro (12.9-inch) (3rd generation)",
# optional
# 5.8" phone
# 4.7" phone
# 4" phone
# 3.5" phone
# 11" pad
# 10.5" pad
# 9.7" pad
])

# A list of languages which should be used
# Note that final entry is language Simulator will be left in after completion
languages([
  "en-US",
])

# The name of the workspace which contains the UI Tests
workspace("MTP.xcworkspace")

# The name of the scheme which contains the UI Tests
scheme("MTPScreenshots")

# Where should the resulting screenshots be stored?
output_directory("./fastlane/screenshots")

# Use multiple Simulators with Xcode 9
# concurrent_simulators(true)

# The directory for derived data reuse
# derived_data_path("/tmp/MTPScreenshots/DerivedData")
# test_without_building(true)

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# configure the Simulator's system language
# localize_simulator(true)

# clean Simulator completely
erase_simulator(false)

# uninstall the application before running it
reinstall_app(false)

# bundle identifier of the app to uninstall (only needed when enabling reinstall_app)
# app_identifier("com.mosttraveledpeople.mtp")

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# save application's logging
# buildlog_path("/tmp/MTPScreenshots/BuildLog")
# output_simulator_logs(true)

# just stop when done
#skip_open_summary(true)

# stop immediately on problems
stop_after_first_error(true)
number_of_retries(0)

# For more information about all available options run
# fastlane action snapshot
