
name: Test
on: [push]

jobs:
  test:
    name: Test
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Test
        run: |
          xcodebuild test -sdk iphonesimulator13.0 -destination 'platform=iOS Simulator,name=iPhone 8' -workspace MTP.xcworkspace -scheme MTP -configuration Debug -derivedDataPath build -enableCodeCoverage YES CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO ARCHS="x86_64" VALID_ARCHS="x86_64" GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
          bash <(bundle exec slather)
        env: 
         destination: 'platform=iOS Simulator,name=iPhone 8'
         DEVELOPER_DIR: /Applications/Xcode_11.app/Contents/Developer
